name: Flowering of Consciousness
favicon: null
layout_spectrum: 0.8624276977498084
typography_spectrum: 0.6686504404060543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
